version: "3"
services: 
  my_postgres: 
    image: postgres:14
    container_name: my_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  etl_project:
    image: travel_time_source_etl:1.0
    depends_on: 
      - my_postgres
    env_file:
      - .env
